### ISSUE TITLE
현재 띄워진 화면으로 재접속 시 오류 발생하는 현상 (Avoided redundant navigation to current location)

### ISSUE THREAD

**Issue by sj1225** [sj1225/voard#1]
## 문제상황
현재 띄워진 화면으로 재접속 시 오류가 발생한다.
ex) HOME 화면에 접속중인 상태에서 또 HOME 메뉴를 클릭하면 아래와 같이 오류 로그 찍힘. HOME > POST나 POST > HOME으로 넘어가는건 정상, HOME > HOME이나 POST > POST와 같이 같은 화면으로 재접속하면 오류 발생.

기능상 문제는 없지만 매우 거슬린다!!! 로그에서는 라우터 중복 접속을 막았다고 하는 것으로 보이는데 그럼 정상적인 현상인가...? 평생 오류 로그를 옷에 묻은 고양이 털처럼 달고 다녀야 하는것인가... 없애는 방법이 있을지 찾아봐야겠다.

![image](https://user-images.githubusercontent.com/49314605/224192419-ed2cc92b-1036-49d7-a1c9-26e8f975afca.png)

## 에러 전문
```
Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/".
    at createRouterError (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2066:15)
    at createNavigationDuplicatedError (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2036:15)
    at HTML5History.confirmTransition (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2334:18)
    at HTML5History.transitionTo (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2261:8)
    at HTML5History.push (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2607:10)
    at eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:3035:22)
    at new Promise (<anonymous>)
    at VueRouter.push (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:3034:12)
    at VueComponent.goHome (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/view/component/Header.vue?vue&type=script&lang=js&:8:20)
    at click (webpack-internal:///./node_modules/vuetify-loader/lib/loader.js??ruleSet[1].rules[0].use!./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/loaders/templateLoader.js??ruleSet[1].rules[4]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/view/component/Header.vue?vue&type=template&id=0a7a53a0&:32:20)
createRouterError @ vue-router.esm.js?3423:2065
createNavigationDuplicatedError @ vue-router.esm.js?3423:2035
confirmTransition @ vue-router.esm.js?3423:2333
transitionTo @ vue-router.esm.js?3423:2260
push @ vue-router.esm.js?3423:2606
eval @ vue-router.esm.js?3423:3034
push @ vue-router.esm.js?3423:3033
goHome @ Header.vue?7035:25
click @ Header.vue?10f9:34
invokeWithErrorHandling @ vue.runtime.esm.js?c320:3017
invoker @ vue.runtime.esm.js?c320:1815
invokeWithErrorHandling @ vue.runtime.esm.js?c320:3017
Vue.$emit @ vue.runtime.esm.js?c320:3716
click @ VTab.ts?e119:97
invokeWithErrorHandling @ vue.runtime.esm.js?c320:3017
invoker @ vue.runtime.esm.js?c320:1815
original_1._wrapper @ vue.runtime.esm.js?c320:7473
```

**Comment by sj1225** [comment]
이슈 적어두고 까먹고있었네!!! 같은 경로로 또 접속하면 발생하는 리다이렉션 오류라고 한다.
라우터 뒤에 catch 문을 추가해주니 오류 로그가 찍히지 않는다!

```
this.$router.push({ /* 생략 */ }).catch(()=>{});
```

### 참고문서
https://sso-feeling.tistory.com/706
